### ISSUE TITLE
Internal Server Error on live site

### ISSUE THREAD

**Issue by martinbaste** [kapil1garg/steam-game-recommender#1]
When entering any Steam ID I'm getting an Internal Server Error. Any ideas on what the problem could be?

**Comment by kapil1garg** [comment]
Hey Martín, thanks for checking this out! The code here hasn’t been maintained for several years. Regarding the live site specifically, it’s likely due to an expired API key. Could also be due to routes on Steam’s end no longer existing. 

What were you looking to do with this? I’m happy to help as much as I can with the open source code, but likely won’t fix any issues in the near future.

**Comment by martinbaste** [comment]
Hi! Just checking if I could use the app live and letting you know that there was a problem with it.
